<?php

namespace MiNutCz\Tree\Enum;

enum KeyCode: int
{
    case KEY_A = 65;
    case KEY_B = 66;
    case KEY_C = 67;
    case KEY_D = 68;
    case KEY_E = 69;
    case KEY_F = 70;
    case KEY_G = 71;
    case KEY_H = 72;
    case KEY_I = 73;
    case KEY_J = 74;
    case KEY_K = 75;
    case KEY_L = 76;
    case KEY_M = 77;
    case KEY_N = 78;
    case KEY_O = 79;
    case KEY_P = 80;
    case KEY_Q = 81;
    case KEY_R = 82;
    case KEY_S = 83;
    case KEY_T = 84;
    case KEY_U = 85;
    case KEY_V = 86;
    case KEY_W = 87;
    case KEY_X = 88;
    case KEY_Y = 89;
    case KEY_Z = 90;
    case KEY_0 = 48;
    case KEY_1 = 49;
    case KEY_2 = 50;
    case KEY_3 = 51;
    case KEY_4 = 52;
    case KEY_5 = 53;
    case KEY_6 = 54;
    case KEY_7 = 55;
    case KEY_8 = 56;
    case KEY_9 = 57;
    case KEY_F1 = 112;
    case KEY_F2 = 113;
    case KEY_F3 = 114;
    case KEY_F4 = 115;
    case KEY_F5 = 116;
    case KEY_F6 = 117;
    case KEY_F7 = 118;
    case KEY_F8 = 119;
    case KEY_F9 = 120;
    case KEY_F10 = 121;
    case KEY_F11 = 122;
    case KEY_F12 = 123;
    case KEY_ESC = 27;
    case KEY_ENTER = 13;
    case KEY_SPACE = 32;
    case KEY_TAB = 9;
    case KEY_BACKSPACE = 8;
    case KEY_SHIFT = 16;
    case KEY_CTRL = 17;
    case KEY_ALT = 18;
    case KEY_CAPS_LOCK = 20;
    case KEY_WINDOWS = 91;
    case KEY_ARROW_UP = 38;
    case KEY_ARROW_DOWN = 40;
    case KEY_ARROW_LEFT = 37;
    case KEY_ARROW_RIGHT = 39;
    case KEY_INSERT = 45;
    case KEY_DELETE = 46;
    case KEY_HOME = 36;
    case KEY_END = 35;
    case KEY_PAGE_UP = 33;
    case KEY_PAGE_DOWN = 34;
    case KEY_NUMPAD_0 = 96;
    case KEY_NUMPAD_1 = 97;
    case KEY_NUMPAD_2 = 98;
    case KEY_NUMPAD_3 = 99;
    case KEY_NUMPAD_4 = 100;
    case KEY_NUMPAD_5 = 101;
    case KEY_NUMPAD_6 = 102;
    case KEY_NUMPAD_7 = 103;
    case KEY_NUMPAD_8 = 104;
    case KEY_NUMPAD_9 = 105;
    case KEY_NUMPAD_MULTIPLY = 106;
    case KEY_NUMPAD_ADD = 107;
    case KEY_NUMPAD_SUBTRACT = 109;
    case KEY_NUMPAD_DECIMAL_POINT = 110;
    case KEY_NUMPAD_DIVIDE = 111;

    public function keyName(): string
    {
       return match ($this) {
            self::KEY_A => 'A',
            self::KEY_B => 'B',
            self::KEY_C => 'C',
            self::KEY_D => 'D',
            self::KEY_E => 'E',
            self::KEY_F => 'F',
            self::KEY_G => 'G',
            self::KEY_H => 'H',
            self::KEY_I => 'I',
            self::KEY_J => 'J',
            self::KEY_K => 'K',
            self::KEY_L => 'L',
            self::KEY_M => 'M',
            self::KEY_N => 'N',
            self::KEY_O => 'O',
            self::KEY_P => 'P',
            self::KEY_Q => 'Q',
            self::KEY_R => 'R',
            self::KEY_S => 'S',
            self::KEY_T => 'T',
            self::KEY_U => 'U',
            self::KEY_V => 'V',
            self::KEY_W => 'W',
            self::KEY_X => 'X',
            self::KEY_Y => 'Y',
            self::KEY_Z => 'Z',
            self::KEY_0 => '0',
            self::KEY_1 => '1',
            self::KEY_2 => '2',
            self::KEY_3 => '3',
            self::KEY_4 => '4',
            self::KEY_5 => '5',
            self::KEY_6 => '6',
            self::KEY_7 => '7',
            self::KEY_8 => '8',
            self::KEY_9 => '9',
            self::KEY_F1 => 'F1',
            self::KEY_F2 => 'F2',
            self::KEY_F3 => 'F3',
            self::KEY_F4 => 'F4',
            self::KEY_F5 => 'F5',
            self::KEY_F6 => 'F6',
            self::KEY_F7 => 'F7',
            self::KEY_F8 => 'F8',
            self::KEY_F9 => 'F9',
            self::KEY_F10 => 'F10',
            self::KEY_F11 => 'F11',
            self::KEY_F12 => 'F12',
            self::KEY_ESC => 'Escape',
            self::KEY_ENTER => 'Enter',
            self::KEY_SPACE => 'Space',
            self::KEY_TAB => 'Tab',
            self::KEY_BACKSPACE => 'Backspace',
            self::KEY_SHIFT => 'Shift',
            self::KEY_CTRL => 'Ctrl',
            self::KEY_ALT => 'Alt',
            self::KEY_CAPS_LOCK => 'Caps Lock',
            self::KEY_WINDOWS => 'Windows',
            self::KEY_ARROW_UP => 'Arrow Up',
            self::KEY_ARROW_DOWN => 'Arrow Down',
            self::KEY_ARROW_LEFT => 'Arrow Left',
            self::KEY_ARROW_RIGHT => 'Arrow Right',
            self::KEY_INSERT => 'Insert',
            self::KEY_DELETE => 'Delete',
            self::KEY_HOME => 'Home',
            self::KEY_END => 'End',
            self::KEY_PAGE_DOWN => 'Page Down',
            self::KEY_PAGE_UP => 'Page Up',
            self::KEY_NUMPAD_0 => 'Numpad 0',
            self::KEY_NUMPAD_1 => 'Numpad 1',
            self::KEY_NUMPAD_2 => 'Numpad 2',
            self::KEY_NUMPAD_3 => 'Numpad 3',
            self::KEY_NUMPAD_4 => 'Numpad 4',
            self::KEY_NUMPAD_5 => 'Numpad 5',
            self::KEY_NUMPAD_6 => 'Numpad 6',
            self::KEY_NUMPAD_7 => 'Numpad 7',
            self::KEY_NUMPAD_8 => 'Numpad 8',
            self::KEY_NUMPAD_9 => 'Numpad 9',
            self::KEY_NUMPAD_MULTIPLY => 'Numpad Multiply',
            self::KEY_NUMPAD_ADD => 'Numpad Add',
            self::KEY_NUMPAD_SUBTRACT => 'Numpad Subtract',
            self::KEY_NUMPAD_DECIMAL_POINT => 'Numpad Decimal Point',
            self::KEY_NUMPAD_DIVIDE => 'Numpad Divide',

        };
    }
}